"""Storage values/interfaces; runtime retains live identities and commit state."""
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Protocol


@dataclass(frozen=True)
class DiskPaths:
    directory: Path
    root: Path
    work: Path | None = None


@dataclass(frozen=True)
class DiskStorageCapabilities:
    root_backend: str
    disk_checkpoint: bool = True
    prepared_fork: bool = True
    publish_diff: bool = False


class DiskStorage(Protocol):
    snapshot_hash: Callable[[Path, str], str]
    hash_file: Callable[[Path], str]
    def capabilities(self, store=None, *, snapshot_mode="full") -> DiskStorageCapabilities: ...
    def prepare(self, catalog: Any, environment_id: str, source: str) -> dict: ...
    def create_writable(self, paths: DiskPaths, source: Path | None, *, sparse=False,
                        store=None, image=None) -> tuple | None: ...
    def checkpoint_disk(self, paths: DiskPaths, staging: Path, target: Path, *,
                        sparse=False, store=None, image=None, device_id=None) -> Path | None: ...
    def restore_disk(self, paths: DiskPaths, snapshot: Path, *, sparse=False,
                     store=None) -> tuple | None: ...
    def release_writable(self, paths: DiskPaths) -> None: ...
    def copy_file(self, source: Path, destination: Path, *, sparse=False, mode=None) -> None: ...
    def verify_checkpoint(self, paths: DiskPaths, snapshot: Path, manifest: dict, *,
                          store=None, source_image=None) -> None: ...
    def service_matches(self, store, device_id, saved_identity) -> bool: ...
    def device_identity(self, store) -> Any: ...
    def release_device(self, store, device_id, runtime, directory, saved_identity) -> None: ...
    def remove_checkpoint(self, path: Path) -> None: ...
    def release_layers(self, directory: Path) -> None: ...
